services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        whatwedo\WorkflowBundle\EventHandler\EventHandlerAbstract:
            tags: ['workflow.event_handler']
            public: true

    whatwedo\WorkflowBundle\:
        resource: '../../*'
        exclude: '../{Entity}'

    'workflow.registry':
        class: whatwedo\WorkflowBundle\Service\WorkflowService
