services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    whatwedo\WorkflowBundle\:
        resource: '../../*'
        exclude: '../{Entity}'

    'workflow.registry':
        class: whatwedo\WorkflowBundle\Service\WorkflowService
