<?php


namespace whatwedo\WorkflowBundle\Form;


use ReflectionClass;
use whatwedo\WorkflowBundle\Entity\Workflowable;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WorkflowSupportedTypes extends AbstractType
{

    public function getParent()
    {
        return ChoiceType::class;
    }


    public function configureOptions(OptionsResolver $resolver)
    {

        $choices = [];

        $classes = get_declared_classes();
        foreach($classes as $klass) {
            $reflect = new ReflectionClass($klass);
            if($reflect->implementsInterface(Workflowable::class)) {
                $choices[$reflect->getShortName()] = $klass;
            }

        }


        $resolver->setDefaults([
            'label' => 'Type',
            'choices' =>
                $choices
            ,
            'multiple' => true
        ]);
        //parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

}